package de.iu.project.iuipwa0201ghostnetfishing.BusinessLayer.Models;

import java.time.Instant;

public class AbandonedNetBusinessLayerModel {
    private Long id;
    private String location;
    private Double size;
    private NetStatusBusinessLayerEnum status;
    private PersonBusinessLayerModel person; // Uses the Person business model
    private Instant createdAt; // Uses java.time.Instant for modern date/time types

    // --- Business Logic ---
    // This is where your application's rules live.

    /**
     * Checks whether a person can be assigned to recover this net.
     * Business rule: assignment is only allowed when status is REPORTED.
     * @return true if assignable, otherwise false.
     */
    public boolean canBeAssigned() {
        return this.status == NetStatusBusinessLayerEnum.REPORTED;
    }

    /**
     * Assigns a person to this net and updates its status.
     * @param person the person to assign.
     * @throws IllegalStateException if the net is not in an assignable state.
     */
    public void assignTo(PersonBusinessLayerModel person) {
        if (!canBeAssigned()) {
            throw new IllegalStateException("Net cannot be assigned in its current state: " + this.status);
        }
        this.person = person;
        this.status = NetStatusBusinessLayerEnum.RECOVERY_PENDING;
    }

    // --- Constructors, Getters and Setters ---
    // (Generated by the IDE)

    public AbandonedNetBusinessLayerModel() {}

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getLocation() { return location; }
    public void setLocation(String location) { this.location = location; }
    public Double getSize() { return size; }
    public void setSize(Double size) { this.size = size; }
    public NetStatusBusinessLayerEnum getStatus() { return status; }
    public void setStatus(NetStatusBusinessLayerEnum status) { this.status = status; }
    public PersonBusinessLayerModel getPerson() { return person; }
    public void setPerson(PersonBusinessLayerModel person) { this.person = person; }
    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }
}
